### ISSUE TITLE
Cannot POST /

### ISSUE THREAD

**Issue by bdQ5xBvJhHUlofLidX** [JustTalDevelops/hcaptcha-solver-api#1]
Heya,

after trying to get the API to work, I'm encountering following error after making a POST request.

`Cannot POST /`

I don't know if I'm just missing something.

The API seems to be running well:
![powershell_K73bpXrIlF](https://user-images.githubusercontent.com/69156028/113592945-1898ce80-9636-11eb-91bb-d370503144cd.png)

This is my Postman config:
![Postman_4BNMeNNFV8](https://user-images.githubusercontent.com/69156028/113592996-29494480-9636-11eb-9edf-9bae629c35f1.png)

And btw, thanks for the amazing work:)!!

**Comment by bdQ5xBvJhHUlofLidX** [comment]
Ah fuck, didn't saw that you have to send it to `/solve`. Sorry! Thanks again for the API:)

**Comment by JustTalDevelops** [comment]
No worries, good luck!
