### ISSUE TITLE
POST request returns "Method not allowed"

### ISSUE THREAD

**Issue by bdQ5xBvJhHUlofLidX** [JustTalDevelops/hcaptcha-solver-api#2]
Heya, me again.

If you send a POST (like how its described in the README) request to `127.0.0.1/solve` it will return `Method Not Allowed`

But if you send a GET request instead, you will get output to the console.
But sending a GET request doesn't seem to work either or I am doing something wrong. I will post the results below.

Maybe its because of this line: https://github.com/JustTalDevelops/hcaptcha-solver-api/blob/8568375d0547ae03cde50def39a6a2133639f747/main.go#L29 (registering a GET instead of POST request?)

I tried to stick to the example with my request from: https://github.com/JustTalDevelops/hcaptcha-solver-go/blob/master/examples/minecraft-pocket-servers/main.go

Sending a POST request:
![Postman_VcGrDV5NpE](https://user-images.githubusercontent.com/69156028/113602433-e3df4400-9642-11eb-8e25-b17951df063f.png)

Sending a GET request (same settings as in POST request):

```bash
 ┌───────────────────────────────────────────────────┐
 │                    Fiber v2.6.0                   │
 │               http://127.0.0.1:8080               │
 │       (bound on host 0.0.0.0 and port 8080)       │
 │                                                   │
 │ Handlers ............. 2  Processes ........... 1 │
 │ Prefork ....... Disabled  PID .............. 9884 │
 └───────────────────────────────────────────────────┘

ERRO[0006] {"c":{"type":"hsl","req":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzIjo2LCJ0IjoicCIsImQiOiJjWnUwR1NYYnJINGpvanBuM3gwRVJySTRTQjZZRmNYdXJnZGhrMGR0Yi9XV1JMa3VLVUpPaUFKaUoxdjZzbTNjNElXYnJLZmFoS1oxaXljS0tIMWhEdVFaWjRpTW9ZRFFzMkJsN1NRYTl4Vm1ra1hrQ3hQdHlxcGtIVkMzdDNacnd0QTF5ODRkNWI2WFZZQlJRQmtSTTRtbmNKSm9kKzlUVGlSWnNhVXJmNWdkeUY0OTZQa1FxZk80b1E9PWtKajNTeVNiWEFaUTFTRGQiLCJsIjoiaHR0cHM6Ly9hc3NldHMuaGNhcHRjaGEuY29tL2MvOTFlMmVhYjUiLCJlIjoxNjE3NjQyNjg1fQ._K8piXCxV8IbZ-6O3AWu7Z2y9T9bPJVBcCpxRS_19i8"},"success":false,"error-codes":[]}
ERRO[0006] {"c":{"type":"hsl","req":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzIjo4LCJ0IjoicCIsImQiOiJiQ1hvWXgyTEVLUEc3NEJXYzlPTzM1NUZqcEw4eHRFRTZiOVlEZ2JZRHdGaG1JWlkzRHhTK2htRjJ4OHZsRkJRa2dyRzhCcndqaDVlOWowSllJYTVldWU2SXIzUjdEZ1JYV3MrSFhWTEZ1Ni8yanRMcVMwSEl2MnBtS0E2QmZzZVFIbWJISVZJcnBTdUNSdi93bmQ1MWFHN3o5OVUwYVdIaWRYWWJyTjNIRGMxNmtac2tiZjZBMFR2UFE9PXI1R2RRbGZwZG5LeW00WkkiLCJsIjoiaHR0cHM6Ly9hc3NldHMuaGNhcHRjaGEuY29tL2MvOTFlMmVhYjUiLCJlIjoxNjE3NjQyNjg1fQ.VZHmJYLUjOL44lp0WQIDbBr15VZ2fWRMph5kHz1mV1E"},"success":false,"error-codes":[]}
ERRO[0007] {"c":{"type":"hsl","req":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzIjo5LCJ0IjoicCIsImQiOiJpMlNWbDBsbnRNRW9JNmRKYVBLVzg4eWROYnBDRUlBeTZQcFVGMi9yaG9tS3VLMTZUL0NRNG9tT0lDdnVWanM1ZmE5c3h6K3Y1dnV4RlJsbzNNZlJnVlJncVZ2c3lkcVZ2UXRhcHk2cDRrS3VJMy92MGx0bDZwNHU5eS9wMXZjYmR3cGNGYzVJSzNMOTRzVWI4YXdzUmRFb1RIajhvY0hXQVo5cEtXcERXeTRBTFArRGlqQnlCSVlnb2c9PThmL0Z0MG9GZ0h2VjRLbDciLCJsIjoiaHR0cHM6Ly9hc3NldHMuaGNhcHRjaGEuY29tL2MvOTFlMmVhYjUiLCJlIjoxNjE3NjQyNjg1fQ.HiZNFsUM00BKlwrK8CNGjHjRwpV4aSqmEZCRa5sNkTo"},"success":false,"error-codes":[]}
ERRO[0007] {"c":{"type":"hsl","req":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzIjoxMCwidCI6InAiLCJkIjoiY0MzSURvT0pST2EzK0Q0dktzajNvUjlHOVNnRTZ1NDYyUXZ1OEVlR01xUHhkS1NMUGU5MGJwbkFzVHB4a1pOdjkxTzUxSThxbGUvcVFjVVBXUnU3MFZvSlpIR2FUN3NIY3d5bmVDblhybC9RM1Z2Ni9XaDhPajQ0OExKb0xtL3pHLzVFaDZHVVdXVHJmbHg5UVgzQkpRSGxpVFBjRzArWFIwaitCeHhvZkN2TXoxV083WVhMbnY3UE1CVT1pWGdlejlackNaaUxhVzFXIiwibCI6Imh0dHBzOi8vYXNzZXRzLmhjYXB0Y2hhLmNvbS9jLzkxZTJlYWI1IiwiZSI6MTYxNzY0MjY4NX0.TWN08oB9XW4_4dCoyxEVt_dKdMbPWbGKrrsHUuV3dng"},"success":false,"error-codes":[]}
ERRO[0007] {"c":{"type":"hsl","req":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzIjoxMiwidCI6InAiLCJkIjoiZFhYajI2Z0pTaHlYaUVxMklSVC9McTV2cmZUWGJDL3pPTTdoU2lGaEVqcGVjUlF1Rm5RbmpYQklQbENqd2JzRXRpbUNwSFRlUE15RjNpRlpFZHZVdVU1TUpqdjA4Z0lzUXRwTFBNbkZwTjV0M3dxaGgvMnpMMms4VGRidzRRT0dxWWdld29kRkFDc1F4ZmJzQnV6VEgyTUFHKzd0U0pLeXhKaE5sMnBKS1ZNeEpVWjdLSWJmVk50V1BvMD1GTmZnUTR5RFdLMXU3OUJGIiwibCI6Imh0dHBzOi8vYXNzZXRzLmhjYXB0Y2hhLmNvbS9jLzkxZTJlYWI1IiwiZSI6MTYxNzY0MjY4Nn0.w0W30u-WgVE5ss6J25LZep3szeUxtnVpV5N3LMaREO8"},"success":false,"error-codes":[]}
ERRO[0007] {"c":{"type":"hsl","req":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzIjoxMywidCI6InAiLCJkIjoiVkJGTzZXYm9jQ1hxZEJUSmVMTk83R2VOcERxQXVKT0M4TS9EUGI5NEJPbVJ2ekhXQnpTNnVKeUhKbU1rM2JlL3BpT3o5Zmk3UFkzeGRJUWd2UnhUNlVHWHNqS1BVTFhhK3BpN05zZmNUelVDcVBaMkRIbStXeXcwRThQaWcrdm5SeGtST1ZKay9hYm1aZWs1bWdwSXArRnFPOWRvb2ttUWdVaGdoc3RzaTFlVXBIbFZwS05CYi9vd0lEaz16eXAwM09VcUdlZHl1eUk1IiwibCI6Imh0dHBzOi8vYXNzZXRzLmhjYXB0Y2hhLmNvbS9jLzkxZTJlYWI1IiwiZSI6MTYxNzY0MjY4Nn0.NzuRE6JemImhy8dhHGyIs8oNdlyFH9IvtoVSqfw4MSM"},"success":false,"error-codes":[]}
```

**Comment by bdQ5xBvJhHUlofLidX** [comment]
Update: 

Yes. The cause of the `Method Not Allowed` error is indeed this line: https://github.com/JustTalDevelops/hcaptcha-solver-api/blob/8568375d0547ae03cde50def39a6a2133639f747/main.go#L29

`Get` should be replaced with `Post` to match the instructions in the README.

But this doesn't solve the errors I'm getting with the API as previously mentioned. I cloned https://github.com/JustTalDevelops/hcaptcha-solver-go and tried to run it and everything was working fine. But in the API, I'm getting those errors.

**Comment by JustTalDevelops** [comment]
Ah, my bad on the GET instead of POST, will fix today.
The errors you are getting in console seem to be from an outdated version of the solver, it seems like I forgot to update it (there were changes as early as yesterday)

I'll fix these issues and get back to you

**Comment by JustTalDevelops** [comment]
Could you try the latest commit and see if it works?

**Comment by bdQ5xBvJhHUlofLidX** [comment]
> Could you try the latest commit and see if it works?

Yeah, it's working now :)! Thanks! I will close the issue

**Comment by bdQ5xBvJhHUlofLidX** [comment]
Oh and @JustTalDevelops just one more thing but it has nothing really todo with this issue. So just ignore it if you dont wan't to answer.

Do you know how to execute hCaptcha after I set the captcha code? Because on my site there isn't any "Submit" button so I have to do it programmatically.  Something like Googles callback function (`___grecaptcha_cfg.clients[0].X.X.callback`)

**Comment by JustTalDevelops** [comment]
No idea, I don't really use any type of web automation software (e.g selenium) but rather pure HTTP requests. Would recommend you just explore around the sites frontend JS and see how it works there.
