### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by andress134** [JustTalDevelops/hcaptcha-solver-api#3]
Hello @JustTalDevelops 
When i try to install it i get this error

# github.com/justtaldevelops/hcaptcha-solver-api
/root/gocode/src/github.com/justtaldevelops/hcaptcha-solver-api/config.go:21:12: undefined: os.ReadFile

**Comment by JustTalDevelops** [comment]
Use Go 1.16

**Comment by JustTalDevelops** [comment]
Also, if you're already using Go, it's pretty pointless to use the API. Just use the library directly

**Comment by JustTalDevelops** [comment]
It just adds another useless middle man which will slow down captcha solving
